# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
Post.create(country: 'Republic of Korea', title: '이름이름이름1', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '1')
Post.create(country: 'Republic of Korea', title: '이름이름이름2', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '2')
Post.create(country: 'Republic of Korea', title: '이름이름이름', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '3')
Post.create(country: 'Republic of Korea', title: '이름이름이름4', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '4')
Post.create(country: 'Republic of Korea', title: '이름이름이름5', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '5')
Post.create(country: 'Republic of Korea', title: '이름이름이름6', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '6')
Post.create(country: 'Republic of Korea', title: '이름이름이름7', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '7')
Post.create(country: 'Republic of Korea', title: '이름이름이름8', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '8')
Post.create(country: 'Republic of Korea', title: '이름이름이름9', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '9')
Post.create(country: 'Republic of Korea', title: '이름이름이름10', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '10')
Post.create(country: 'Republic of Korea', title: '이름이름이름11', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '11')
Post.create(country: 'Republic of Korea', title: '이름이름이름12', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '12')
Post.create(country: 'Republic of Korea', title: '이름이름이름13', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '13')
Post.create(country: 'Republic of Korea', title: '이름이름이름14', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '14')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '15')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '16')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '17')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '18')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '19')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '20')
Post.create(country: 'Republic of Korea', title: '이름이름이름1', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '21')
Post.create(country: 'Republic of Korea', title: '이름이름이름2', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '22')
Post.create(country: 'Republic of Korea', title: '이름이름이름', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '23')
Post.create(country: 'Republic of Korea', title: '이름이름이름4', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '24')
Post.create(country: 'Republic of Korea', title: '이름이름이름5', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '25')
Post.create(country: 'Republic of Korea', title: '이름이름이름6', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '26')
Post.create(country: 'Republic of Korea', title: '이름이름이름7', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '27')
Post.create(country: 'Republic of Korea', title: '이름이름이름8', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '28')
Post.create(country: 'Republic of Korea', title: '이름이름이름9', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '29')
Post.create(country: 'Republic of Korea', title: '이름이름이름10', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '30')
Post.create(country: 'Republic of Korea', title: '이름이름이름11', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '31')
Post.create(country: 'Republic of Korea', title: '이름이름이름12', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '32')
Post.create(country: 'Republic of Korea', title: '이름이름이름13', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '33')
Post.create(country: 'Republic of Korea', title: '이름이름이름14', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '1:1 대화방', image: '34')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '35')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '36')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '37')
Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '38')

#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '39')
#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '40')
#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '41')
#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '42')
#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '43')
#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '44')
#Post.create(country: 'Republic of Korea', title: '이름이름이름15', content: '#축구 #스키장',filter: "0", address: 'https://open.kakao.com/o/g9vkySp', people: '그룹대화방', image: '45')